apiVersion: v1
kind: Service
metadata:
  name: duke-user-consumer-service
  labels:
    app.kubernetes.io/name: duke-user-consumer-service
    app.kubernetes.io/instance: duke-user-consumer-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: duke-user-consumer-service
    app.kubernetes.io/instance: duke-user-consumer-service
